### ISSUE TITLE
Language Server Crashes on Package Load

### ISSUE THREAD

**Issue by D-Maxwell** [savetheclocktower/pulsar-ide-typescript-alpha#4]
hello there ;

![Image](https://github.com/user-attachments/assets/43266e34-1bad-4d5e-ac60-8a73e69ec8dd)

upon launching pulsar, past having installed and absolutely referenced node, this is the crash i am greeted with.

[debug-0.log](https://github.com/user-attachments/files/18825870/2025-02-17T13_20_47_285Z-debug-0.log)

not much to make out of this log, yet it's all i could find.

**Comment by savetheclocktower** [comment]
Open the developer tools and run

```js
atom.config.set('core.debugLSP', true);
```

then reload your window. The next time the language server tries and fails to start up, you should end up with much more information in your developer tools console. If you are able to figure out the issue and get the server running, you can then flip `core.debugLSP` back to `false`. If not, post the output here and I'll see what I can do.

When sorting through the things logged to the console, you should look for messages that mention `TypeScript Language Server`; anything else will be irrelevant to this problem. You can filter the console output on a particular word or phrase if that helps.

**Comment by D-Maxwell** [comment]
> Open the developer tools and run
> 
> atom.config.set('core.debugLSP', true);

thanks for the tip. i appreciate it.

```

TypeScript/JavaScript (TypeScript Language Server) stderr C:\Users\<me>\.pulsar\packages\pulsar-ide-typescript-alpha\node_modules\.bin\typescript-language-server:2
TypeScript/JavaScript (TypeScript Language Server) stderr basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
TypeScript/JavaScript (TypeScript Language Server) stderr ^^^^^^^
2
TypeScript/JavaScript (TypeScript Language Server) stderr
TypeScript/JavaScript (TypeScript Language Server) stderr SyntaxError: missing ) after argument list
TypeScript/JavaScript (TypeScript Language Server) stderr at wrapSafe (node:internal/modules/cjs/loader:1666:18)
TypeScript/JavaScript (TypeScript Language Server) stderr at Module._compile (node:internal/modules/cjs/loader:1708:20)
TypeScript/JavaScript (TypeScript Language Server) stderr at Object..js (node:internal/modules/cjs/loader:1899:10)
TypeScript/JavaScript (TypeScript Language Server) stderr at Module.load (node:internal/modules/cjs/loader:1469:32)
TypeScript/JavaScript (TypeScript Language Server) stderr at Function._load (node:internal/modules/cjs/loader:1286:12)
TypeScript/JavaScript (TypeScript Language Server) stderr at TracingChannel.traceSync (node:diagnostics_channel:322:14)
TypeScript/JavaScript (TypeScript Language Server) stderr at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
TypeScript/JavaScript (TypeScript Language Server) stderr at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:151:5)
TypeScript/JavaScript (TypeScript Language Server) stderr at node:internal/main/run_main_module:33:47
TypeScript/JavaScript (TypeScript Language Server) stderr Node.js v23.8.0
TypeScript/JavaScript (TypeScript Language Server) rpc.onClose
```

not sure what that initial error might be about ; surely it couldn't have to do with the script at `~\.pulsar\packages\pulsar-ide-typescript-alpha\node_modules\.bin\typescript-language-server` somehow missing a closing parenthesis, which it quite simply does not.

oddly enough, unless node bundled bash, shouldn't the script run here end up being that ending in `.bat`, as prioritised by the os of my machine, over that lacking an extension ?
i may add that i have a cygwin-esque devkit installed, a mini installation meant mostly for bash and gcc, which, although not supposed to be called unless explicitly, may have been.

(edit : attempting to start the language server with said devkit excluded from the path made no difference.)

**Comment by savetheclocktower** [comment]
> oddly enough, unless node bundled bash, shouldn't the script run here end up being that ending in `.bat`, as prioritised by the os of my machine, over that lacking an extension ?

When you open `C:\Users\<me>\.pulsar\packages\pulsar-ide-typescript-alpha\node_modules\.bin\` and view the contents, do you see a `.bat` file in there?

This is baffling to me because I don't know where the quoted snippet comes from. It's quite clearly a bashism, ~~but you're right that there's nothing that looks like that in the `typescript-language-server` binary.~~

Are you able to run `[the path you specified to your node.exe] C:\Users\<me>\.pulsar\packages\pulsar-ide-typescript-alpha\node_modules\.bin\typescript-language-server` in a terminal without the same error appearing?

I dread the words I'm about to type, but it sounds like I might have to double-check that this package works in Windows. But, man, it would be hard for me to imagine that that's the problem; Node abstracts away a lot of that stuff.

**Comment by savetheclocktower** [comment]
OK, here's a [very similar issue](https://github.com/zed-industries/zed/issues/21834) on Zed.

Now that I see [the entire binary stub](https://github.com/truckermudgeon/maps/issues/37) (found via a code search), it looks to me like a bash script that assumes it's being run on Windows and is trying to tell the difference between being run in Cygwin/MinGW versus being run in WSL. The idea that it would be executed from `cmd.exe` or PowerShell appears to be unenvisioned.

On macOS, that binstub doesn't exist at all; the `.bin` folder holds symlinks to the files being invoked (which themselves are prefaced with `#!/usr/bin/env node` shebangs.

Of course, the tool responsible for generating that binstub is `ppm`, so I'm not thrilled with this. I will continue to investigate.

**Comment by savetheclocktower** [comment]
I'm hoping that I've interpreted your post correctly, and that there is also a `.bat` present with the same name in that `.bin` directory… because that seems like it would be Node's halfway-elegant solution for this situation (a binary working properly on Windows whether it's called from `cmd.exe`, PowerShell, Cygwin, MinGW, or WSL). If so, I can whip up a fix for you pretty quickly.

**Comment by D-Maxwell** [comment]
> > oddly enough, unless node bundled bash, shouldn't the script run here end up being that ending in `.bat`, as prioritised by the os of my machine, over that lacking an extension ?
> 
> When you open `C:\Users\<me>\.pulsar\packages\pulsar-ide-typescript-alpha\node_modules\.bin\` and view the contents, do you see a `.bat` file in there?

every bash script present in there has both a batch `.cmd` (not `.bat` for some reason, iirc there's no relevant difference.) alternative as well as a powershell one.

as doubt began to grow, i decided to check this for myself ; and the batch shell does in fact search for explicit batch files over their non-extended counterparts (i.e. running `hellothere` will target `hellothere.bat` over `hellothere` (no extension) were both accessible)


may we exclude nodejs potentially bundling and making use of its own bash shell ? i have not found anything of the like in its files.
but then, why --and how, lacking an interpreter-- would the logs point to the bash script specifically, rather than the batch one ?

**Comment by D-Maxwell** [comment]
> Are you able to run `[the path you specified to your node.exe] C:\Users\<me>\.pulsar\packages\pulsar-ide-typescript-alpha\node_modules\.bin\typescript-language-server` in a terminal without the same error appearing?

i bring forth progress !

i think.

i hope.

i can't seem to run the package outside of its usual pulsar environment either.

running `node %userprofile%\.pulsar\packages\pulsar-ide-typescript-alpha\node_modules\.bin\typescript-language-server` results in... the same error !

not sure what to make of this.

here's the log, although it is pretty much the same as that already supplied
```
C:\Users\<me>\.pulsar\packages\pulsar-ide-typescript-alpha\node_modules\.bin\typescript-language-server:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at wrapSafe (node:internal/modules/cjs/loader:1666:18)
    at Module._compile (node:internal/modules/cjs/loader:1708:20)
    at Object..js (node:internal/modules/cjs/loader:1899:10)
    at Module.load (node:internal/modules/cjs/loader:1469:32)
    at Function._load (node:internal/modules/cjs/loader:1286:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:151:5)
    at node:internal/main/run_main_module:33:47

Node.js v23.8.0
```

**Comment by savetheclocktower** [comment]
> but then, why --and how, lacking an interpreter-- would the logs point to the bash script specifically, rather than the batch one ?

Because the bash script has no extension. I'm basically running

```
[path to your node] [path-to-the-package]/node_modules/.bin/typescript-language-server
```

which leaves it up to Node to infer which file I want to execute.

I imagine that, if I were just running

```
[path-to-the-package]/node_modules/.bin/typescript-language-server
```

the shell would use its own semantics that would lead it to choose `typescript-language-server.cmd` or `typescript-language-server.ps` over a bare `typescript-language-server`. (I mean, you didn't have to type the `.exe` in DOS, so that's hardly new; never been in a situation where I wanted the shell to prefer `foo.exe` or `foo.cmd` over a file just called `foo` in the same directory, but I suppose it follows logically.)

So the fix here is to do something similar to what that bin stub is doing, only a bit smarter:

* on macOS or Linux, execute `typescript-language-server` (with no extension) no matter what.
* on Windows… I think I can just use the `.cmd` all the time? But perhaps sniff what sort of shell I'm running in just to be sure? I'm spawning a child process from within Pulsar's copy of Node, and if we're on Windows that's probably going to work the same way no matter how Pulsar was spawned, but I'll make sure.

That means this package has definitely been broken for Windows users at least since I made it a bring-your-own-Node type thing. That is lamentable. I will fix it.

Thanks so much for the report!

**Comment by D-Maxwell** [comment]
> > but then, why --and how, lacking an interpreter-- would the logs point to the bash script specifically, rather than the batch one ?
> 
> Because the bash script has no extension. I'm basically running
> 
> ```
> [path to your node] [path-to-the-package]/node_modules/.bin/typescript-language-server
> ```
> 
> which leaves it up to Node to infer which file I want to execute.
> 
> I imagine that, if I were just running
> 
> ```
> [path-to-the-package]/node_modules/.bin/typescript-language-server
> ```
> 
> the shell would use its own semantics that would lead it to choose `typescript-language-server.cmd` or `typescript-language-server.ps` over a bare `typescript-language-server`. (I mean, you didn't have to type the `.exe` in DOS, so that's hardly new; never been in a situation where I wanted the shell to prefer `foo.exe` or `foo.cmd` over a file just called `foo` in the same directory, but I suppose it follows logically.)

that, unless i am missing a crucial element, sounds like an upstream --node-- issue to be honest...

given that node already has some kind of infrastructure meant to make use of the os' potential preference for explicit scripts over bare files, shouldn't your code already run platform agnostically by that logic, were node to process the supplied path with respect to os preferences ?

of course, a temporary workaround to mitigate this oversight would not be unwelcome, especially as i was in the midst of developing a pulsar package (remember translucency ? i have not surrendered just yet 😊)

**Comment by savetheclocktower** [comment]
BTW, you can try this out yourself if you're impatient: find [this line](https://github.com/savetheclocktower/pulsar-ide-typescript-alpha/blob/main/lib/main.js#L176) at (I imagine) `C:\Users\<me>\.pulsar\packages\pulsar-ide-typescript-alpha\lib\main.js` and temporarily change it to `typescript-language-server.cmd`. Then reload your Pulsar window — if it works, then you can reap the benefits without waiting for a package update.

EDIT: Wait, that's mad. Never mind. I'm prefixing `node`, which means I should just point to the main `.js` file. I'm dumb. Bear with me.

**Comment by savetheclocktower** [comment]
> given that node already has some kind of infrastructure meant to make use of the os' potential preference for explicit scripts over bare files, shouldn't your code already run platform agnostically by that logic, were node to process the supplied path with respect to os preferences ?

Actually, Node is doing the right thing here, and I'm the one who screwed up by assuming I could run `node .bin/[something]` in a cross-platform way just because it happens to work on macOS and Linux.

**Comment by D-Maxwell** [comment]
> Actually, Node is doing the right thing here, and I'm the one who screwed up by assuming I could run `node .bin/[something]` in a cross-platform way just because it happens to work on macOS and Linux.

that's exactly my point. if such files are already present, why isn't node making use of them ? shouldn't the path given as an argument to node be evaluated according to os specifications ?

**Comment by savetheclocktower** [comment]
> > Actually, Node is doing the right thing here, and I'm the one who screwed up by assuming I could run `node .bin/[something]` in a cross-platform way just because it happens to work on macOS and Linux.
> 
> that's exactly my point. if such files are already present, why isn't node making use of them ? shouldn't the path given as an argument to node be evaluated according to os specifications ?

No, Node expects that argument to be a JavaScript file, not an executable.

**Comment by savetheclocktower** [comment]
Anyway, try changing the line to

```js
let bin = Path.join(ROOT, 'node_modules', 'typescript-language-server', 'lib', 'cli.mjs');
```

and see if that fixes it after a window reload.

**Comment by D-Maxwell** [comment]
> No, Node expects that argument to be a JavaScript file, not an executable.

my bad, i thought you were running `node ~\.pulsar\packages\pulsar-ide-typescript-alpha\node_modules\.bin\typescript-language-server`, not the package entry point.

i must've got confused at some point. i'm lost.

**Comment by savetheclocktower** [comment]
> > No, Node expects that argument to be a JavaScript file, not an executable.
> 
> my bad, i thought you were running `node ~\.pulsar\packages\pulsar-ide-typescript-alpha\node_modules\.bin\typescript-language-server`, not the package entry point.
> 
> i must've got confused at some point. i'm lost.

I was, and amazingly that _works_ on macOS and Linux.

On macOS, everything in `.bin` is just symlinked to the stuff in various folders. Here's the entirety of my `.bin/typescript-language-server`:

```
#!/usr/bin/env node
import fs$l, { promises, statSync, existsSync, readFileSync as readFileSync$1 } from 'node:fs';

function writeToLog(message) {
	fs.appendFileSync(`/Users/andrew/Code/Atom/pulsar-ide-typescript-alpha/debug.log`, message)
}

import require$$0 from 'events';

import require$$1 from 'child_process';
```

This only works because Node recognizes the bash shebang and ignores it. This allows you to write an executable shell script with an initial shebang and run it as either `./foo.js` or `node foo.js`, much like with other scripting languages.

**Comment by D-Maxwell** [comment]
> Anyway, try changing the line to
> 
> let bin = Path.join(ROOT, 'node_modules', 'typescript-language-server', 'lib', 'cli.mjs');
> 
> and see if that fixes it after a window reload.

yup, that solved it !

**Comment by D-Maxwell** [comment]
> I was, and amazingly that _works_ on macOS and Linux.
> 
> On macOS, everything in `.bin` is just symlinked to the stuff in various folders.
> This only works because Node recognizes the bash shebang and ignores it. This allows you to write an executable shell script with an initial shebang and run it as either `./foo.js` or `node foo.js`, much like with other scripting languages.

well, at least i'm not insane. that did make absolutely no sense.

how come your package structure differs depending on the platform it is "built" for ?
was that a consequence of ppm ?

(also, don't linux and windows filesystems support symlinks ? why should the structure differ to this extent ? does it have to do with execution time perhaps ?)

**Comment by savetheclocktower** [comment]
Before we keep discussing this: I just pushed a new version of this package. See if it fixes your problem.

**Comment by D-Maxwell** [comment]
> Before we keep discussing this: I just pushed a new version of this package. See if it fixes your problem.

i somehow messed up badly.

i couldn't update as relevant resources were locked ; so i closed the pulsar tab in which i had opened your package's entry point, restarted the app just to make sure, and now the package is nothing more than the remnants of itself ; a ghost package, if you will.

![Image](https://github.com/user-attachments/assets/ed755a73-4b47-4d71-af09-4aa35249b087)

may i simply force delete the directory, or are there other manipulations specific to pulsar outside of the files' existence to be executed in order to properly uninstall a package ?

(uninstalling fails silently, and the option to update is gone.)

**Comment by D-Maxwell** [comment]
ok so, i forced the deletion of leftover files which pulsar couldn't get rid of for some reason.

i was able to reinstall the package in a seemingly clean manner.


however.

the dreaded.

the eye-prying.

the fearsome.

the hair-pulling.

![Image](https://github.com/user-attachments/assets/3be6957d-6631-4dcf-bef1-4d37762d8123)

so uh, that update did not solve it.



wait. hold on.

why

![Image](https://github.com/user-attachments/assets/00432013-f318-4b78-913e-7e867c40f0a2)

**Comment by D-Maxwell** [comment]
for some reason installing packages does not fetch the latest release, and will instead prefer to prompt you for updates post installation.

not sure why that is. is there some kind of buffer in between, with the main pulsar packages repo being the source from which one installs packages, whilst updating packages is handled through package specific urls ?

anyway, that *did* fix it.

thank you for your patience haha

**Comment by savetheclocktower** [comment]
Probably just a cache that's slow to invalidate! Your difficulties might've been because I told you to change a file locally; if you did that and left it open, that'd explain the lock.

Anyway. The answers to your other questions are too long to explain and involve critical differences in shell behavior between Windows and Unix, so I'll kindly refer you to Google or your favorite chatbot.

**Comment by D-Maxwell** [comment]
> Anyway. The answers to your other questions are too long to explain and involve critical differences in shell behavior between Windows and Unix, so I'll kindly refer you to Google or your favorite chatbot.

right, sorry for bothering you. i was mostly confused about the way in which ppm worked, i'll have a look at that. i'll need to in not too long.

funny how it turned out a bodge had been holding the package together this entire time.

anyway, have a great day ! it's getting late over here.
